[connection]
ethereum_rpc_url = "https://eth-mainnet.g.alchemy.com/v2/KLmJncAMynx8Eh5-vueyu8oEOEw1o60n"
wss_node_endpoint = "wss://eth-mainnet.g.alchemy.com/v2/ytR4n5_A2voAHiE99XJkCDKsgO4XCt-q"
flashbots_url = "https://relay.flashbots.net"
#ethereum_rpc_url = "https://eth-sepolia.g.alchemy.com/v2/Rjy3brdwjWzejidRH9GxgeFbHBxZhsBe"
#flashbots_url = "https://relay-sepolia.flashbots.net"             
builders_url = [
    "https://rpc.beaverbuild.org/",
    "https://rpc.titanbuilder.xyz",
    "https://builder0x69.io",
    "https://mev.api.blxrbdn.com",
    "https://buildai.net/",
    "https://api.blocknative.com/v1/auction",
    "https://eth-builder.com/",
    "https://boba-builder.com/searcher/bundle",
    "https://rpc.payload.de",
    "https://api.edennetwork.io/v1/bundle",
    "https://builder.eigenphi.io/",
    "https://rpc.lokibuilder.xyz/",
    "https://relay.flashbots.net",
    "https://builder.flashbots.net",
    "https://builder.ethermine.org",
]

[contract]
address = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"
uniswap_v2_router = "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
uniswap_v3_router = "0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD"
weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
#uniswap_v2_router = "0xC532a74256D3Db42D0Bf7a0400fEFDbad7694008"         
#weth = "0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9"        


[bundle] #0.000000002  =2gwei
bundler_key = ""
priority_fee = 0.000000003
miner_tip = 0
retries = 10
delay_s = 20


[sniper] #0.01 = 1% , 0.0099 0.99%
buyback = 0.0099
max_limit = 0.0099

private_keys = []
